f=open("fruits.txt")
content=f.read()
print(content)
print("---------------------------------------------------------------------------")
f=open("fruits.txt","w")
f.write("Eat 5 Star")
f.write(" Do Nothing....\n")
f.write("Hi Bro\n")
f.close()
print("---------------------------------------------------------------------------")
f=open("fruits.txt","r+") #r+ => read and write 
print(f.read())
print("---------------------------------------------------------------------------")
f=open("fruits.txt","a")
f.write("5Star")
f.write("Hotel....\n")
f.close()
print("---------------------------------------------------------------------------")
f=open("fruits.txt","r+") #r+ => read and write 
print(f.read())
print("---------------------------------------------------------------------------")
